apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
data:
  index.html: |
    <body>
      <h1>Hello World!</h1>
      <p>Good Bye.</p>
    </body>

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.3
          ports:
            - containerPort: 80
          volumeMounts:
            - name: volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: volume
          configMap:
            name: index-html
